# Generated by Django 3.0.5 on 2020-05-02 11:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name_plural': 'Adds'},
        ),
        migrations.AlterModelOptions(
            name='calculate',
            options={'verbose_name_plural': 'Calculations'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History'},
        ),
        migrations.AlterField(
            model_name='add',
            name='value',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,\\ (-)?\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
